### PR TITLE
Minor bug fixes

### PR DESCRIPTION
**Pull request by godiennie**
Fix real_name
Added more information about bans

### CODE REVIEW

**Comment by kenddie** [comment]
I noticed this and changed - https://github.com/smiley/steamapi/pull/46/commits/5083139a40b9818824549e8f6956e39ecac9948d

**Comment by smiley** [comment]
No, I meant the prefix is wrong. `is_` means `True/False`.

**Comment by huwcbjones** [comment]
Since changes have been made, can this be merged?

**Comment by godiennie** [comment]
Yeah.

2018-01-29 18:45 GMT+03:00 Huw Jones <notifications@github.com>:

**Comment by smiley** [comment]
Sure, just forgot about it.

**Pull request merged**
